language: java

install: 
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu saucy main universe"
  - sudo apt-get update -q
  - sudo apt-get install -y gcc-4.8-arm-linux-gnueabihf 


script: mvn clean install -DskipTests -Dcompiler.exec=arm-linux-gnueabihf-gcc-4.8 -Dlinker.exec=arm-linux-gnueabihf-ld

jdk:
  - oraclejdk8
  - oraclejdk7

notifications:
  email:
    - pipistik.bunciak@gmail.com

branches:
  only:
    - master
